version: '3'

services:
  db:
    container_name: pg_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ROOT
      POSTGRES_PASSWORD: ROOT
      POSTGRES_DB:  my_db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "venskijnik@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    restart: always


